### ISSUE TITLE
Support different output per prospectors group

### ISSUE THREAD

**Issue by tanapoln** [Graylog2/collector-sidecar#158]
### Problem description
Let assumed that we have collector-sidecar which configured with tag `linux` and `docker`.
Then, add 2 configurations which the first one match label `linux` and the second one match label `docker`

For the first one, set FileBeat output with host `['graylog-server:5044']` and set Input file as path `/var/lib/docker/containers/*/*-json.log`.
For the second one, set FileBeat output with host `['graylog-server:5045']` and set Input file as path `/var/log/*.log`.

Then, I inspect generated filebeat configuration is like below:

```YAML
filebeat:
  prospectors:
  - document_type: docker
    encoding: utf-8
    fields:
      gl2_source_collector: 3c87a1e4-ae1d-4f8b-9a37-13d2aec86e2d
    ignore_older: 0
    input_type: log
    paths:
    - /var/lib/docker/containers/*/*-json.log
    scan_frequency: 10s
    tail_files: true
  - document_type: syslog
    encoding: plain
    fields:
      gl2_source_collector: 3c87a1e4-ae1d-4f8b-9a37-13d2aec86e2d
    ignore_older: 0
    input_type: log
    paths:
    - /var/log/*.log
    scan_frequency: 10s
    tail_files: true
output:
  logstash:
    hosts:
    - graylog-server:5045
    loadbalance: false
path:
  data: /var/cache/graylog/collector-sidecar/filebeat/data
  logs: /var/log/graylog/collector-sidecar
tags:
- linux
- docker
```

As you can see, there is only single output host.

### What result should look like
I don't know if filebeat support separated output per group of prospectors. What I expect is that each prospectors should send to different output in isolation, which is the first prospector (docker) should send to `graylog-server:5044` without sending to `graylog-server:5045` and vice versa.

### Environment

* Sidecar Version: 0.1.0
* Graylog Version: 2.2.2
* Operating System: Amazon Linux
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3
