### ISSUE TITLE
NxLog backend finished unexpectedly

### ISSUE THREAD

**Issue by aremai** [Graylog2/collector-sidecar#161]
### Problem description
I have NxLog configured as my backend, the nxlog.conf looks like this:

```
User nxlog
Group nxlog

LogFile /var/log/nxlog/nxlog.log
LogLevel INFO

########################################
# Modules                              #
########################################
<Extension _syslog>
    Module      xm_syslog
</Extension>

<Input in1>
    Module      im_udp
    Port        1515
    Exec        parse_syslog_bsd();
    Host        0.0.0.0
    Exec        if $raw_event =~ /^(.+)Message forwarded from (.+)/ $raw_event = $1 + $2;
    Exec        parse_syslog();
    Exec        if not defined($SourceIP) $SourceIP=$MessageSourceAddress;\
                if not defined($type) $Type='SYSLOG/UDP';
</Input>

<Output fileout1>
    Module      om_file
    File        "/var/log/nxlog/logmsg.txt"
    Exec        if $Message =~ /error/ $SeverityValue = syslog_severity_value("error");
    Exec        to_syslog_bsd();
</Output>

<Output fileout2>
    Module      om_file
    File        "/var/log/nxlog/logmsg2.txt"
</Output>

########################################
# Routes                               #
########################################
<Route 1>
    Path        in1 => fileout1
</Route>
```

and the sidecar-collector.yml looks like this:

```
server_url: http://127.0.0.1:9000/api/
update_interval: 10
tls_skip_verify: false
send_status: true
list_log_files:
   - /var/log
node_id: graylog-collector-sidecar
collector_id: file:/etc/graylog/collector-sidecar/collector-id
cache_path: /var/cache/graylog/collector-sidecar
log_path: /var/log/graylog/collector-sidecar
log_rotation_time: 86400
log_max_age: 604800
tags:
    - linux
backends:
    - name: nxlog
      enabled: true
      binary_path: /usr/bin/nxlog
      configuration_path: /etc/nxlog/nxlog.conf
```

I'm seeing the following error:

```
time="2017-04-11T17:21:44+02:00" level=info msg="Stopping signal distributor"
time="2017-04-11T17:21:44+02:00" level=info msg="Starting signal distributor"
time="2017-04-11T17:21:44+02:00" level=info msg="[nxlog] Starting (exec driver)"
time="2017-04-11T17:21:45+02:00" level=error msg="[nxlog] Backend finished unexpectedly, trying to restart 1/3."
time="2017-04-11T17:21:45+02:00" level=info msg="[nxlog] Stopping"
time="2017-04-11T17:21:47+02:00" level=info msg="[nxlog] Starting (exec driver)"
time="2017-04-11T17:21:48+02:00" level=error msg="[nxlog] Backend finished unexpectedly, trying to restart 2/3."
time="2017-04-11T17:21:48+02:00" level=info msg="[nxlog] Stopping"
time="2017-04-11T17:21:50+02:00" level=info msg="[nxlog] Starting (exec driver)"
time="2017-04-11T17:21:51+02:00" level=error msg="[nxlog] Backend finished unexpectedly, trying to restart 3/3."
time="2017-04-11T17:21:51+02:00" level=info msg="[nxlog] Stopping"
```

What am I doing wrong here?

My environment/setup is as follow (I'm using the latest Graylog virtual appliance)

### Environment

* Sidecar Version: 0.1.0-1
* Graylog Version: 2.2.3-1
* Operating System: Ubuntu 14.04
* Elasticsearch Version:
* MongoDB Version:
