### ISSUE TITLE
Invalid event log key "event_id" windows server 2003

### ISSUE THREAD

**Issue by faxonnet** [Graylog2/collector-sidecar#165]
### Problem description
the same configuration work on windows 2008 r2
on windows 2003r2 server
level=error msg="[winlogbeat] Error during configuration validation: Exiting: Failed to create new event log. 1 error: Invalid event log key **'event_id'** found. Valid keys are api, fields, fields_under_root, format_buffer_size, ignore_older, name, read_buffer_size, tags\n" 

generated conf: 
```
fields:
  collector_node_id: test-2003
  gl2_source_collector: 369fe5e4-9d66-49f7-a7fe-1f15f9cfe054
output:
  logstash:
    hosts:
    - 10.23.0.65:5044
path:
  data: C:\Program files\graylog\collector-sidecar\cache\winlogbeat\data
  logs: C:\Program files\graylog\collector-sidecar\logs
tags:
- EventViewer
winlogbeat:
  event_logs:
  - name: CustomProgram
  - name: Security
    event_id: 528-540, 551
```
### Environment

* Sidecar Version:
0.1.1-1 latest 
* Graylog Version:
* Operating System:
* Elasticsearch Version:
* MongoDB Version:
