### ISSUE TITLE
multi tag  snippet error

### ISSUE THREAD

**Issue by faxonnet** [Graylog2/collector-sidecar#166]
### Problem description
if i configure 2 tag  windows, custom_app
and i create snippet foreach tag 
this is the result
```
winlogbeat:
  event_logs:
  - name: windows
  - name: custom_app
    event_id: 528-540, 551, 552, 672-680, 682, 683, 4627, 4650-4655, 4771, 4772, 4777-4779, 4820, 4964, 4976-4984, 5378, 5451-5453, 5632, 5633, 6272-6280, 4663, 5145, 4624
    event_id: 17105-17108, 17105-17108, 17425-17428, 17352, 17354, 17354, 17366, 17367, 17385, 17383, 17418, 17396, 17378, 17379, 17419, 17397, 17398, 17399, 17394, 17415, 17416, 17417, 17377, 17456, 17601, 17602-17606, 17672-17675
```

### Steps to reproduce the problem

1- create 2 configuration for collectors with different tag and different snippet 
2- assign this 2 tag to one collector
### Environment

* Sidecar Version:
* Graylog Version:
* Operating System:
* Elasticsearch Version:
* MongoDB Version:

**Comment by joschi** [comment]
@faxonnet Please elaborate on what problem you actually have.

**Comment by faxonnet** [comment]
what do you mean? 
collector_sidecar_installer have a problem with snippet....
collector_sidecar_installer put in wrong place snippet
This would be the correct format
 **- name: windows**
    **event_id:** 528-540, 551, 552, 672-680, 682, 683, 4627, 4650-4655, 4771, 4772, 4777-4779, 4820, 4964, 4976-4984, 5378, 5451-5453, 5632, 5633, 6272-6280, 4663, 5145, 4624
**- name: custom_app**
   
d be the correct format
 **- name: windows**
    **event_id:** 528-540, 551, 552, 672-680, 682, 683, 4627, 4650-4655, 4771, 4772, 4777-4779, 4820, 4964, 4976-4984, 5378, 5451-5453, 5632, 5633, 6272-6280, 4663, 5145, 4624
**- name: custom_app**
    **event_id:** 17105-17108, 17105-17108, 17425-17428, 17352, 17354, 17354, 17366, 17367, 17385, 17383, 17418, 17396, 17378, 17379, 17419, 17397, 17398, 17399, 17394, 17415, 17416, 17417, 17377, 17456, 17601, 17602-17606, 17672-17675

**Comment by mariussturm** [comment]
@faxonnet the snippets are basically just text that is added at the end of a configuration. They dont respect any yaml structure.
If you want to select specific events for collection you have to use the `Event name` field. E.g. if you put '[{'name':'Windows', 'event_id':'528-540'},{'name':'cutome_app', 'event_id':'17105-17108'}]` into the configuration it will rendered to:

```
winlogbeat:
  event_logs:
  - event_id: 528-540
    name: Windows
  - event_id: 17105-17108
    name: cutome_app
```

You have to make sure that the configured event do exist otherwise Winlogbeat refuses to start.
