### ISSUE TITLE
Empty configuration is inserted before snippet if no input/output configured

### ISSUE THREAD

**Issue by dziedrius** [Graylog2/collector-sidecar#208]
### Problem description

When there is no collector input/output defined in collector's configuration for filebeat on graylog website, using snippets is not possible, because empty configuration would be inserted before actual snippet.

### Steps to reproduce the problem

1. Create collector configuration in System>Collectors
2. Define only snippet for filebeat (no input/output)
3. Add snipet with file beats configuration
4. Notice on client, where sidecar service is deployed, that filebeat.yml contains empty configuration first, then snippet, example:
```
filebeat:
  prospectors: []
path:
  data: C:\Program Files\graylog\collector-sidecar\cache\filebeat\data
  logs: C:\Program Files\graylog\collector-sidecar\logs
tags:
- windows
- iis
- custom
filebeat:
  prospectors:
  - encoding: plain
    fields:
      collector_node_id: graylog-collector-sidecar
      gl2_source_collector: collector-guid
      type: log
    ignore_older: 0
    paths:
    - C:\temp\log.txt
    scan_frequency: 10s
    tail_files: true
    type: log
    json.keys_under_root:true
output:
  logstash:
    hosts:
    - graylog.local:5044
path:
  data: C:\Program Files\graylog\collector-sidecar\cache\filebeat\data
  logs: C:\Program Files\graylog\collector-sidecar\logs
tags:
- windows
- iis
- custom
``` 

### Environment

* Sidecar Version: collector_sidecar_installer_0.1.4-1.exe
* Graylog Version: Graylog 2.3.1+9f2c6ef
* Operating System: Windows 10
