### ISSUE TITLE
filebeat.yml and winlogbeat.yml are not existing or generated

### ISSUE THREAD

**Issue by KhaledSMQ** [Graylog2/collector-sidecar#216]
### Problem description
generated\filebeat.yml and generated\winlogbeat.yml are not existing or generated
I am getting error
```
level=error msg="GetFileAttributesEx C:\\graylog\\collector-sidecar\\generated: The system cannot find the path specified."
```

### Steps to reproduce the problem

1. ...

```
(AS Administrator )

C:\Program Files\Graylog\collector-sidecar>Graylog-collector-sidecar.exe -debug
time="2018-01-10T21:27:37-08:00" level=info msg="Using collector-id: 739c0000-a57b-4936-bb0c-863edb7b8bf8"
time="2018-01-10T21:27:37-08:00" level=info msg="Fetching configurations tagged by: [windows iis]"
time="2018-01-10T21:27:37-08:00" level=debug msg="Creating rotated log writer for: C:\\Program Files\\graylog\\collector-sidecar\\logs\\collector_sidecar.log.%Y%m%d%H%M"
time="2018-01-10T21:27:37-08:00" level=debug msg="Add collector backend: winlogbeat"
time="2018-01-10T21:27:37-08:00" level=error msg="GetFileAttributesEx C:\\graylog\\collector-sidecar\\generated: The system cannot find the path specified."
time="2018-01-10T21:27:37-08:00" level=debug msg="Add collector backend: filebeat"
time="2018-01-10T21:27:37-08:00" level=error msg="GetFileAttributesEx C:\\graylog\\collector-sidecar\\generated: The system cannot find the path specified."
time="2018-01-10T21:27:37-08:00" level=info msg="Starting signal distributor"
time="2018-01-10T21:27:37-08:00" level=debug msg="[signal-processor] (seq=1) handling cmd: restart"
time="2018-01-10T21:27:37-08:00" level=debug msg="[signal-processor] (seq=1) handling cmd: restart"
time="2018-01-10T21:27:37-08:00" level=info msg="[winlogbeat] Starting (exec driver)"
time="2018-01-10T21:27:37-08:00" level=info msg="[filebeat] Starting (exec driver)"
time="2018-01-10T21:27:37-08:00" level=debug msg="Creating rotated log writer for: C:\\Program Files\\graylog\\collector-sidecar\\logs\\winlogbeat_stderr.log.%Y%m%d%H%M"
time="2018-01-10T21:27:37-08:00" level=debug msg="Creating rotated log writer for: C:\\Program Files\\graylog\\collector-sidecar\\logs\\filebeat_stderr.log.%Y%m%d%H%M"
time="2018-01-10T21:27:37-08:00" level=debug msg="Creating rotated log writer for: C:\\Program Files\\graylog\\collector-sidecar\\logs\\winlogbeat_stderr.log.%Y%m%d%H%M"
time="2018-01-10T21:27:37-08:00" level=debug msg="Creating rotated log writer for: C:\\Program Files\\graylog\\collector-sidecar\\logs\\filebeat_stderr.log.%Y%m%d%H%M"
time="2018-01-10T21:27:37-08:00" level=debug msg="[signal-processor] (seq=1) cmd done: restart"
time="2018-01-10T21:27:37-08:00" level=debug msg="[signal-processor] (seq=1) cmd done: restart"
time="2018-01-10T21:27:38-08:00" level=error msg="[winlogbeat] Backend finished unexpectedly, trying to restart 1/3."
time="2018-01-10T21:27:38-08:00" level=debug msg="[signal-processor] (seq=2) handling cmd: restart"
time="2018-01-10T21:27:38-08:00" level=info msg="[winlogbeat] Stopping"
time="2018-01-10T21:27:38-08:00" level=error msg="[filebeat] Backend finished unexpectedly, trying to restart 1/3."
time="2018-01-10T21:27:38-08:00" level=debug msg="[signal-processor] (seq=2) handling cmd: restart"
time="2018-01-10T21:27:38-08:00" level=info msg="[filebeat] Stopping"
time="2018-01-10T21:27:40-08:00" level=info msg="Stopping signal distributor"
time="2018-01-10T21:27:40-08:00" level=debug msg="[winlogbeat] SIGHUP ignored, killing process"
time="2018-01-10T21:27:40-08:00" level=debug msg="[winlogbeat] Failed to kill process invalid argument"
time="2018-01-10T21:27:40-08:00" level=info msg="[winlogbeat] Starting (exec driver)"
time="2018-01-10T21:27:40-08:00" level=debug msg="Creating rotated log writer for: C:\\Program Files\\graylog\\collector-sidecar\\logs\\winlogbeat_stderr.log.%Y%m%d%H%M"
time="2018-01-10T21:27:40-08:00" level=debug msg="Creating rotated log writer for: C:\\Program Files\\graylog\\collector-sidecar\\logs\\winlogbeat_stderr.log.%Y%m%d%H%M"
time="2018-01-10T21:27:40-08:00" level=debug msg="[signal-processor] (seq=2) cmd done: restart"
time="2018-01-10T21:27:40-08:00" level=debug msg="[signal-processor] (seq=3) handling cmd: shutdown"
time="2018-01-10T21:27:40-08:00" level=info msg="[winlogbeat] Stopping"
time="2018-01-10T21:27:40-08:00" level=debug msg="[filebeat] SIGHUP ignored, killing process"
time="2018-01-10T21:27:40-08:00" level=debug msg="[filebeat] Failed to kill process invalid argument"
time="2018-01-10T21:27:40-08:00" level=info msg="[filebeat] Starting (exec driver)"
time="2018-01-10T21:27:40-08:00" level=debug msg="Creating rotated log writer for: C:\\Program Files\\graylog\\collector-sidecar\\logs\\filebeat_stderr.log.%Y%m%d%H%M"
time="2018-01-10T21:27:40-08:00" level=debug msg="Creating rotated log writer for: C:\\Program Files\\graylog\\collector-sidecar\\logs\\filebeat_stderr.log.%Y%m%d%H%M"
time="2018-01-10T21:27:40-08:00" level=debug msg="[signal-processor] (seq=2) cmd done: restart"
time="2018-01-10T21:27:40-08:00" level=debug msg="[signal-processor] (seq=3) handling cmd: shutdown"
time="2018-01-10T21:27:40-08:00" level=info msg="[filebeat] Stopping"


```
### Environment

* Sidecar Version: Graylog Collector Sidecar version 0.1.4 (edd1e1d) [go1.8.3/amd64]
* Graylog Version:
* Operating System: Windows Server 2012
* Elasticsearch Version:
* MongoDB Version:

**Comment by jalogisch** [comment]
@KhaledSMQ 

did you generate a configuration in Graylog with a *tag* that is configured in your collector-sidecar configuration? (that would be `windows` or `iis` according to your logfile.

If that is the case we need more verbose Information about your configuration (the config files would be a good start. I'll close this now, if you feel that this is wrong - please reopen.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by KhaledSMQ** [comment]
@jalogisch 
in config file i have already tagged windows, iis already before start the application you can see that in debug log
``` 
time="2018-01-10T21:27:37-08:00" level=info msg="Fetching configurations tagged by: [windows iis]"
```

**Comment by KhaledSMQ** [comment]
here is configurations
```
server_url: http://log.local:9000/api 
update_interval: 10
tls_skip_verify: false
send_status: true
list_log_files:
node_id: graylog-collector-sidecar
collector_id: file:C:\Program Files\graylog\collector-sidecar\collector-id
cache_path: C:\Program Files\graylog\collector-sidecar\cache
log_path: C:\Program Files\graylog\collector-sidecar\logs
log_rotation_time: 86400
log_max_age: 604800
tags: [windows, iis]
backends:
    - name: nxlog
      enabled: false
      binary_path: C:\Program Files (x86)\nxlog\nxlog.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\nxlog.conf
    - name: winlogbeat
      enabled: true
      binary_path: C:\Program Files\graylog\collector-sidecar\winlogbeat.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\winlogbeat.yml
    - name: filebeat
      enabled: true
      binary_path: C:\Program Files\graylog\collector-sidecar\filebeat.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\filebeat.yml

```

**Comment by joschi** [comment]
@KhaledSMQ Try putting the paths in double quotes.

Example:

```yaml
backends:
    - name: nxlog
      enabled: false
      binary_path: "C:\Program Files (x86)\nxlog\nxlog.exe"
      configuration_path: "C:\Program Files\graylog\collector-sidecar\generated\nxlog.conf"
```
