### ISSUE TITLE
Command Line Flags Issue

### ISSUE THREAD

**Issue by javillerenas** [Graylog2/collector-sidecar#229]
### Problem description
When installing using the Command Line, the options `NXLOG_ENABLED`, `WINLOGBEAT_ENABLED` , and `FILEBEAE_ENABLED` do not work.

This happened both in a Windows Server.

### Steps to reproduce the problem
Install using the following command:
 `$ collector_sidecar_installer.exe /S -SERVERURL=<server_URL> -TAGS="my_tag" -NXLOG_ENABLED=true -WINLOGBEAT_ENABLED=true -FILEBEAE_ENABLED=true`

### Environment

* Sidecar Version: `0.1.5`
* Operating System: `Windows 2008 R2`

**Comment by mariussturm** [comment]
The installer flags only work on Windows. How does the collector_sidecar.yml file looks like after the installer ran?

**Comment by javrllerenas** [comment]
You're right, I was trying the flags on Windows.

The file `collector_sidecar.yml` looks as follows:
```
server_url: http://<server_URL>/api/
update_interval: 10
...
log_max_age: 604800
tags:
    - ['Windows', 'IIS']   # Not sure if these were the default tags. I changed them manually
backends:
    - name: nxlog
      enabled: false
     ...
    - name: filebeat
      enabled: true
      ...
    - name: winlogbeat
      enabled: true
      ...
```

As mentioned in the comment, I am not sure which ones were the default tags, since I had to change them manually. However, I can tell you that the tags that I used in the command were not updated, nor where the setting of `nxlog` to `true` and the rest to `false`
