### ISSUE TITLE
Add default log collector templates

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/collector-sidecar#297]
We should ship 3.0 including proper templates for all log collectors.
Compiling these up by hand is quite cumbersome.

Among other sane defaults, they should include the fields setting, so that one
can filter messages from a specific sidecar:
```  
   fields:
      collector_node_id: ${nodeId}
      gl2_source_collector: ${nodeName}
      type: log
```
