### ISSUE TITLE
Update sidecar documentation for Graylog 3.0

### ISSUE THREAD

**Issue by bernd** [Graylog2/collector-sidecar#317]
The sidecar documentation needs to be adjusted for the new sidecar system in 3.0.

http://docs.graylog.org/en/3.0/pages/collector_sidecar.html

**Comment by mpfz0r** [comment]
Starting a list of things we should document, so they're not forgotten:

 - They "Show messages" button will only work, if
  a) The `Beats` input is used and the beats collector configuration contains:
    > fields_under_root: true
    > fields.collector_node_id: ${sidecar.nodeName}
    > fields.gl2_source_collector: `${sidecar.nodeId}``

   b) The `Beats (deprecated)` input is used and the beats collector config contains:
     > fields_under_root: false
     > fields.collector_node_id: ${sidecar.nodeName}
     > fields.gl2_source_collector: `${sidecar.nodeId}``

**Comment by mariussturm** [comment]
Basic installation and usage:

  * Install the Sidecar package
  * Select a proper collector and install it
  * Edit sidecar.yml and first start
  * Create a collector backend in Graylog
  * Create a collector configuration in Graylog
  * Assign configurations to Sidecars
  * Use process commands to administrate collectors

**Comment by ion-storm** [comment]
the installer requires an API key, we need documentation on which api key is needed for this.

**Comment by ion-storm** [comment]
Also is their self signed certificate support? I only seem to be able to get unencrypted logging working with the new sidecar.

**Comment by mpfz0r** [comment]
> Also is their self signed certificate support? I only seem to be able to get unencrypted logging working with the new sidecar.

Yes, there is support for TLS. There hasn't been much change to the old sidecar in this regard.
You still need to create your own keys and certificates, and deploy them to your servers that are running the sidecar. The only difference is that in the new sidecar, you need to write your own collector configuration.
Beats collectors for example need a section like this to enable TLS:

```
output.logstash:
   hosts: ["172.16.1.1:5044"]
   ssl.certificate_authorities: ["/etc/graylog/sidecar/keys/mpfca.crt"]
   ssl.certificate: "/etc/graylog/sidecar/keys/beatsclient.crt"
   ssl.key: "/etc/graylog/sidecar/keys/beatsclient.key"
```
Ideally you would setup your Graylog server with TLS as well. This secures the communication between the Sidecars and Graylog.
