### ISSUE TITLE
Incorrect config for winlogbeat with TLS connections

### ISSUE THREAD

**Issue by michaelanthon** [Graylog2/collector-sidecar#51]
### Problem description
winlogbeats configuraton for TLS output includes an empty certificate_authorities entry that causes it to fail.  Excluding the CA entry when no CA file is configured will fix this issue

```
output:
  logstash:
    hosts:
    - graylog.example.com:5044
    tls:
      certificate_authorities:
      - ""
      insecure: true
```
### Steps to reproduce the problem

1. Configure wnlogbeats collector output with "Enable TLS support" and "Insecure TLS connection" both enabled

### Environment

* Sidecar Version: 0.0.9 (Windows amd64)
* Graylog Version: 2.1.0-1
* Operating System: Linux
* Elasticsearch Version:
* MongoDB Version:
