### ISSUE TITLE
Collector writes invalid filebeat configuration (yml syntax problem)

### ISSUE THREAD

**Issue by sysadmin1337** [Graylog2/collector-sidecar#75]
### Problem description

Collector writes invalid filebeat configuration

### Steps to reproduce the problem

1. Start sidecar collector

/etc/graylog/collector-sidecar/generated/filebeat.yml turns out to be:

```
filebeat:
  prospectors:
  - document_type: log
    fields:
      gl2_source_collector: xxx
    ignore_older: 0
    input_type: log
    paths:
    - /var/log/syslog
    scan_frequency: 10s
    tail_files: true
output:
  logstash:
    hosts: '[192.168.1.43:5044'']'
```

Should probably be:

```
output:
  logstash:
    hosts: ["192.168.1.43:5044"]
```

Don't know for sure yet, still debugging this and trying to get logs in graylog for the first time.

### Environment

* Sidecar Version: 0.0.9
* Graylog Version: v2.1.1 (Docker image)
* Operating System: Ubuntu 16.04
* Elasticsearch Version: elasticsearch:2 (Docker image)
* MongoDB Version: mongo:3 (Docker image)

**Comment by mariussturm** [comment]
Could you please append a screenshot of the output configuration in the Graylog web interface?

**Comment by sysadmin1337** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/22659660/19153746/06af26c8-8bd8-11e6-88eb-d9fba5c77411.png)
![selection_003](https://cloud.githubusercontent.com/assets/22659660/19153792/384b4ce8-8bd8-11e6-9b9c-734cead7b9a7.png)

**Comment by sysadmin1337** [comment]
When changing the filebeat configuration and debugging again it changes back to the old (wrong) configuration

**Comment by sysadmin1337** [comment]
Anything else you want me to post?

**Comment by mariussturm** [comment]
Sorry, I meant the output of the Filebeat configuration so that I can reproduce the probelm. Go to System->Collectors->Manage configurations-><Your configuration>->Edit output. Modal pops up, the `Hosts` field is interesting for me.

**Comment by sysadmin1337** [comment]
![selection_006](https://cloud.githubusercontent.com/assets/22659660/19154465/e6277b6e-8bda-11e6-9a48-5509d2aa32e2.png)
![selection_007](https://cloud.githubusercontent.com/assets/22659660/19154483/f80d1ffa-8bda-11e6-8851-258c89cee78c.png)

It's the same as in the filebeat configuration.

**Comment by sysadmin1337** [comment]
```
server_url: http://192.168.1.43:9000/api/
update_interval: 10
tls_skip_verify: false
send_status: true
list_log_files:
node_id: graylog-collector-sidecar
collector_id: file:/etc/graylog/collector-sidecar/collector-id
log_path: /var/log/graylog/collector-sidecar
log_rotation_time: 86400
log_max_age: 604800
tags:
    - syslog
backends:
    - name: filebeat
      enabled: true
      binary_path: /usr/bin/filebeat
      configuration_path: /etc/graylog/collector-sidecar/generated/filebeat.yml
```
collector_sidecar.yml for completeness
