### ISSUE TITLE
Version 0.1.0 error

### ISSUE THREAD

**Issue by MrSlayers** [Graylog2/collector-sidecar#79]
### Steps to reproduce the problem

1. Install version 0.1.0
2. Configure "collector_sidecar.yml" correctly !
2. Launch and nxlog crash

ERRO[0022] [nxlog] Collector exits immediately, this should not happen! Please check your collector configuration!

Other test : 

1. Update version Working 0.0.9 to 0.1.0 
2. Relaunch
3. Nxlog crash

ERRO[0022] [nxlog] Collector exits immediately, this should not happen! Please check your collector configuration!

### Environment

* Sidecar Version: 0.1.0
* Graylog Version: 2.1
* Operating System: Centos7

**Comment by joschi** [comment]
@MrSlayers Please attach your `collector_sidecar.yml` file and the generated nxlog configuration.

**Comment by mariussturm** [comment]
@MrSlayers and the generated nginx.conf from both sidecar versions is needed to debug this.

**Comment by MrSlayers** [comment]
collector_sidecar.yml

```
server_url: http://192.168.10.56:12900/api/
update_interval: 10
tls_skip_verify: false
send_status: true
node_id: graylog-collector-sidecar-lxcorafr12
collector_id: file:/etc/graylog/collector-sidecar/collector-id
log_path: /var/log/graylog/collector-sidecar
log_rotation_time: 86400
log_max_age: 604800
tags:
    - linux
    - apache
backends:
    - name: nxlog
      enabled: true
      binary_path: /usr/bin/nxlog
      configuration_path: /etc/graylog/collector-sidecar/generated/nxlog.conf

```

nxlog.conf (sidecar version 0.0.9)
```
define ROOT /usr/bin

<Extension gelf>
  Module xm_gelf
</Extension>



User nxlog
Group nxlog
Moduledir /usr/libexec/nxlog/modules
CacheDir /var/spool/collector-sidecar/nxlog
PidFile /var/run/graylog/collector-sidecar/nxlog.pid
define LOGFILE /var/log/graylog/collector-sidecar/nxlog.log
LogFile %LOGFILE%
LogLevel INFO

<Extension logrotate>
    Module  xm_fileop
    <Schedule>
        When    @daily
        Exec    file_cycle('%LOGFILE%', 7);
     </Schedule>
</Extension>




<Input 57fb9a8ac3420b7c543ddd48>
        Module im_file
        File '/home/logs/wwwcoradrivefr-access_*.log'
        PollInterval 1
        SavePos True
        ReadFromLast True
        Recursive True
        RenameCheck False
        Exec $FileName = file_name(); # Send file name with each message
</Input>




<Output 57fb9a4cc3420b7c543ddd06>
        Module om_udp
        Host 192.168.10.56
        Port 12203
        OutputType  GELF
        Exec $short_message = $raw_event; # Avoids truncation of the short_message field.
        Exec $gl2_source_collector = '270754c3-72f4-4407-87bb-347d4a3b973a';
        Exec $Hostname = hostname_fqdn();
</Output>



<Route route-0>
  Path 57fb9a8ac3420b7c543ddd48 => 57fb9a4cc3420b7c543ddd06
</Route>

```
nxlog.conf (sidecar version 0.1.0)
```
define ROOT /usr/bin

<Extension gelf>
  Module xm_gelf
</Extension>



User nxlog
Group nxlog
Moduledir /usr/libexec/nxlog/modules
CacheDir /var/spool/collector-sidecar/nxlog
PidFile /var/run/graylog/collector-sidecar/nxlog.pid
define LOGFILE /var/log/graylog/collector-sidecar/nxlog.log
LogFile %LOGFILE%
LogLevel INFO

<Extension logrotate>
    Module  xm_fileop
    <Schedule>
        When    @daily
        Exec    file_cycle('%LOGFILE%', 7);
     </Schedule>
</Extension>




<Input 57fb9a8ac3420b7c543ddd48>
        Module im_file
        File '/home/logs/wwwcoradrivefr-access_*.log'
        PollInterval 1
        SavePos True
        ReadFromLast True
        Recursive True
        RenameCheck False
        Exec $FileName = file_name(); # Send file name with each message
</Input>




<Output 57fb9a4cc3420b7c543ddd06>
        Module om_udp
        Host 192.168.10.56
        Port 12203
        OutputType  GELF
        Exec $short_message = $raw_event; # Avoids truncation of the short_message field.
        Exec $gl2_source_collector = '270754c3-72f4-4407-87bb-347d4a3b973a';
        Exec $Hostname = hostname_fqdn();
</Output>



<Route route-0>
  Path 57fb9a8ac3420b7c543ddd48 => 57fb9a4cc3420b7c543ddd06
</Route>

```

IN "/var/log/graylog/collector-sidecar/nxlog_stderr.log.201610110200"
`Failed to open config file "/etc/graylog/collector-sidecar/generated/nxlog.conf";No such file or directory
`

Downgrade to 0.0.9 work fine
